//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: System.Reflection.AssemblyTitleAttribute("")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Code generated by ScreenMaker - Internal version 20.4.9280.0")]
[assembly: System.Reflection.AssemblyCompanyAttribute("")]
[assembly: System.Reflection.AssemblyProductAttribute("")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("")]
[assembly: System.Reflection.AssemblyTrademarkAttribute("")]
[assembly: System.Reflection.AssemblyCultureAttribute("")]
[assembly: System.Reflection.AssemblyVersionAttribute("6.12.184")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("20.4.9280.0")]
[assembly: ABB.Robotics.Tps.Taf.TpsViewAttribute("HMI - Proyecto Final", "tpu-Operator32.png", "tpu-Operator32.png", "TpsViewHMI.dll", "HMI.MainScreen", ABB.Robotics.Tps.Taf.StartPanelLocation.Left, ABB.Robotics.Tps.Taf.TpsViewType.Static, ABB.Robotics.Tps.Taf.TpsViewStartupTypes.Manual)]


