//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace HMI
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led2;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel8;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led2 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led3 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.pictureBox2 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font15b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(106, 54);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(240, 39);
            this.tpsLabel1.Title = "Robótica UN 2021-I";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(310, 294);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(286, 34);
            this.tpsLabel2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel2.Title = "Camilo Andrés Zorro Mendoza";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(310, 315);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(286, 28);
            this.tpsLabel3.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel3.Title = "Juan David Ramírez Salazar";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(310, 349);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(286, 26);
            this.tpsLabel4.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel4.Title = "Ana María Rodríguez Reyes";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font8;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(310, 334);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(286, 20);
            this.tpsLabel5.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel5.Title = "John Alejandro Hernández Mora";
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(382, 54);
            this.tpsLabel6.Multiline = true;
            this.tpsLabel6.Name = "tpsLabel6";
            this.tpsLabel6.Size = new System.Drawing.Size(177, 24);
            this.tpsLabel6.Title = "HMI - Proyecto final";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(3, 54);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(97, 58);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            // 
            // led1
            // 
            this.led1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("DI_NuevaSilla")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(373, 110);
            this.led1.Name = "led1";
            this.led1.Size = new System.Drawing.Size(177, 20);
            this.led1.Text = "New Chair available";
            // 
            // led2
            // 
            this.led2.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("DI_SillaEnBanda")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.led2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led2.Location = new System.Drawing.Point(373, 136);
            this.led2.Name = "led2";
            this.led2.Size = new System.Drawing.Size(177, 20);
            this.led2.Text = "Chair in band";
            // 
            // led3
            // 
            this.led3.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("DI_SillaEntregada")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.led3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led3.Location = new System.Drawing.Point(373, 162);
            this.led3.Name = "led3";
            this.led3.Size = new System.Drawing.Size(177, 20);
            this.led3.Text = "Chair delivered";
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(126, 362);
            this.tpsLabel7.Multiline = true;
            this.tpsLabel7.Name = "tpsLabel7";
            this.tpsLabel7.Size = new System.Drawing.Size(143, 13);
            this.tpsLabel7.Title = "Facultad de Ingeniería";
            // 
            // tpsLabel8
            // 
            this.tpsLabel8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.tpsLabel8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel8.Location = new System.Drawing.Point(106, 339);
            this.tpsLabel8.Multiline = true;
            this.tpsLabel8.Name = "tpsLabel8";
            this.tpsLabel8.Size = new System.Drawing.Size(177, 17);
            this.tpsLabel8.Title = "Depto. Mecánica y Mecatrónica";
            // 
            // pictureBox2
            // 
            this.pictureBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(35, 127);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(299, 191);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button1.Location = new System.Drawing.Point(349, 223);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(114, 50);
            this.button1.Text = "Start";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(469, 223);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(106, 50);
            this.button2.Text = "Stop";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.button2);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.pictureBox2);
            this.Controls.Add(this.tpsLabel8);
            this.Controls.Add(this.tpsLabel7);
            this.Controls.Add(this.led3);
            this.Controls.Add(this.led2);
            this.Controls.Add(this.led1);
            this.Controls.Add(this.tpsLabel6);
            this.Controls.Add(this.tpsLabel5);
            this.Controls.Add(this.tpsLabel4);
            this.Controls.Add(this.tpsLabel3);
            this.Controls.Add(this.tpsLabel2);
            this.Controls.Add(this.tpsLabel1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.Controls.SetChildIndex(this.tpsLabel1, 0);
            this.Controls.SetChildIndex(this.tpsLabel2, 0);
            this.Controls.SetChildIndex(this.tpsLabel3, 0);
            this.Controls.SetChildIndex(this.tpsLabel4, 0);
            this.Controls.SetChildIndex(this.tpsLabel5, 0);
            this.Controls.SetChildIndex(this.tpsLabel6, 0);
            this.Controls.SetChildIndex(this.led1, 0);
            this.Controls.SetChildIndex(this.led2, 0);
            this.Controls.SetChildIndex(this.led3, 0);
            this.Controls.SetChildIndex(this.tpsLabel7, 0);
            this.Controls.SetChildIndex(this.tpsLabel8, 0);
            this.Controls.SetChildIndex(this.pictureBox2, 0);
            this.Controls.SetChildIndex(this.button1, 0);
            this.Controls.SetChildIndex(this.button2, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void runRoutineButton1_BeforeRunRoutine(object sender, System.ComponentModel.CancelEventArgs e)
        {
            try
            {
                // Calling SignalSet
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/DO_nuevaSilla"))).Set();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in runRoutineButton1_BeforeRunRoutine", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
                e.Cancel = true;
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalSet
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/DO_nuevaSilla"))).Set();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling SignalSet
                ((ABB.Robotics.Controllers.IOSystemDomain.DigitalSignal)(ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetSignal(this, "IOSYSTEM/SIGNALS/DO_STOP"))).Set();
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // Store variables
                // 
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
