//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace HMI
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.PictureBox pictureBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led1;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led2;
        
        private ABB.Robotics.Tps.Windows.Forms.Led led3;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel7;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel8;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton runRoutineButton1;
        
        private ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton runRoutineButton2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.pictureBox1 = new ABB.Robotics.Tps.Windows.Forms.PictureBox();
            this.led1 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led2 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.led3 = new ABB.Robotics.Tps.Windows.Forms.Led();
            this.tpsLabel7 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel8 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.runRoutineButton1 = new ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton();
            this.runRoutineButton2 = new ABB.Robotics.ScreenMaker.Windows.Forms.RunRoutineButton();
            this.SuspendLayout();
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font15b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(73, 54);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(240, 39);
            this.tpsLabel1.Title = "Robótica UN 2021-I";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(339, 266);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(240, 24);
            this.tpsLabel2.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel2.Title = "Camilo Andrés Zorro Mendoza";
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(339, 296);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(240, 21);
            this.tpsLabel3.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel3.Title = "Juan David Ramírez Salazar";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(339, 323);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(240, 20);
            this.tpsLabel4.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel4.Title = "Ana María Rodríguez Reyes";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(339, 349);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(240, 20);
            this.tpsLabel5.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel5.Title = "John Alejandro Hernández Mora";
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(373, 69);
            this.tpsLabel6.Multiline = true;
            this.tpsLabel6.Name = "tpsLabel6";
            this.tpsLabel6.Size = new System.Drawing.Size(177, 24);
            this.tpsLabel6.Title = "HMI - Proyecto final";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(73, 85);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(194, 232);
            // 
            // led1
            // 
            this.led1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("DI_NuevaSilla")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.led1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led1.Location = new System.Drawing.Point(373, 115);
            this.led1.Name = "led1";
            this.led1.Size = new System.Drawing.Size(177, 20);
            this.led1.Text = "New Chair available";
            // 
            // led2
            // 
            this.led2.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("DI_SillaEnBanda")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.led2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led2.Location = new System.Drawing.Point(373, 141);
            this.led2.Name = "led2";
            this.led2.Size = new System.Drawing.Size(177, 20);
            this.led2.Text = "Chair in band";
            // 
            // led3
            // 
            this.led3.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.SignalObject("DI_SillaEntregada")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.led3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font9;
            this.led3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.led3.Location = new System.Drawing.Point(373, 167);
            this.led3.Name = "led3";
            this.led3.Size = new System.Drawing.Size(177, 20);
            this.led3.Text = "Chair delivered";
            // 
            // tpsLabel7
            // 
            this.tpsLabel7.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11;
            this.tpsLabel7.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel7.Location = new System.Drawing.Point(73, 349);
            this.tpsLabel7.Multiline = true;
            this.tpsLabel7.Name = "tpsLabel7";
            this.tpsLabel7.Size = new System.Drawing.Size(194, 20);
            this.tpsLabel7.Title = "Facultad de Ingeniería";
            // 
            // tpsLabel8
            // 
            this.tpsLabel8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11;
            this.tpsLabel8.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel8.Location = new System.Drawing.Point(73, 323);
            this.tpsLabel8.Multiline = true;
            this.tpsLabel8.Name = "tpsLabel8";
            this.tpsLabel8.Size = new System.Drawing.Size(228, 24);
            this.tpsLabel8.Title = "Depto. Mecánica y Mecatrónica";
            // 
            // runRoutineButton1
            // 
            this.runRoutineButton1.BackColor = System.Drawing.Color.White;
            this.runRoutineButton1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.runRoutineButton1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.runRoutineButton1.Location = new System.Drawing.Point(339, 205);
            this.runRoutineButton1.Name = "runRoutineButton1";
            this.runRoutineButton1.RoutineToCall = new ABB.Robotics.ScreenMaker.Windows.Forms.RoutineDataObject("T_ROB1", "Module1", "start");
            this.runRoutineButton1.Size = new System.Drawing.Size(106, 42);
            this.runRoutineButton1.Text = "Start";
            this.runRoutineButton1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // runRoutineButton2
            // 
            this.runRoutineButton2.BackColor = System.Drawing.Color.White;
            this.runRoutineButton2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.runRoutineButton2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.runRoutineButton2.Location = new System.Drawing.Point(474, 205);
            this.runRoutineButton2.Name = "runRoutineButton2";
            this.runRoutineButton2.Size = new System.Drawing.Size(105, 43);
            this.runRoutineButton2.Text = "Stop";
            this.runRoutineButton2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.runRoutineButton2);
            this.Controls.Add(this.runRoutineButton1);
            this.Controls.Add(this.tpsLabel8);
            this.Controls.Add(this.tpsLabel7);
            this.Controls.Add(this.led3);
            this.Controls.Add(this.led2);
            this.Controls.Add(this.led1);
            this.Controls.Add(this.tpsLabel6);
            this.Controls.Add(this.tpsLabel5);
            this.Controls.Add(this.tpsLabel4);
            this.Controls.Add(this.tpsLabel3);
            this.Controls.Add(this.tpsLabel2);
            this.Controls.Add(this.tpsLabel1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.SetChildIndex(this.pictureBox1, 0);
            this.Controls.SetChildIndex(this.tpsLabel1, 0);
            this.Controls.SetChildIndex(this.tpsLabel2, 0);
            this.Controls.SetChildIndex(this.tpsLabel3, 0);
            this.Controls.SetChildIndex(this.tpsLabel4, 0);
            this.Controls.SetChildIndex(this.tpsLabel5, 0);
            this.Controls.SetChildIndex(this.tpsLabel6, 0);
            this.Controls.SetChildIndex(this.led1, 0);
            this.Controls.SetChildIndex(this.led2, 0);
            this.Controls.SetChildIndex(this.led3, 0);
            this.Controls.SetChildIndex(this.tpsLabel7, 0);
            this.Controls.SetChildIndex(this.tpsLabel8, 0);
            this.Controls.SetChildIndex(this.runRoutineButton1, 0);
            this.Controls.SetChildIndex(this.runRoutineButton2, 0);
            this.ResumeLayout(false);
        }
        #endregion
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // Store variables
                // 
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
